### ISSUE TITLE
import image from Windows

### ISSUE THREAD

**Issue by kashkoulimohammad** [Japhiolite/bqcs#2]
Hello Jan,

First of all, thank you for your suggestion. 
I am using windows and I could not import an image into bqpick.
This error happened:
`SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 0-1: truncated \UXXXXXXXX escape`
and these are my scripts:
`import sys
sys.path.append('C:')
import bqpick
import numpy as np
img = bqpick.import_cs('\Users\mamali\Desktop\New folder\2d_cross section.png')
xdim = np.array([0.,12000.])
zdim = np.array([4000., -1000.])
sc = bqpick.set_cs_dim(xdim, zdim)
fig = bqpick.add_del(sc, img)`

Best regards,
Mohammad

**Comment by Japhiolite** [comment]
Hi Mohammad,

this error comes from the single backslash `\Users`.  `\U...` is used for marking a unicode character. You can fix this by either using double \\ or use a read statement `r"\Users\mamali\Desktop\New folder\2d_cross section.png"` before the string.

See here for a more detailed explanation: https://stackoverflow.com/questions/1347791/unicode-error-unicodeescape-codec-cant-decode-bytes-cannot-open-text-file

Cheers
Jan

**Comment by kashkoulimohammad** [comment]
Thank you for your help.
